import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ShopProvider } from "@/context/ShopContext"; // 👈 import your context
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Le Mon Noire",
  icons: {
    icon: "/img/bgLemon.svg",
    shortcut: "/img/bgLemon.svg",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <ShopProvider> {/* ✅ wrap entire app */}
          {children}
        </ShopProvider>
      </body>
    </html>
  );
}
